tengine 2.0.3-r2, the 1st release

diff --git a/tengine/initd b/tengine/initd
--- a/tengine/initd
+++ b/tengine/initd
@@ -1,68 +1,73 @@
-#!/bin/sh
+#!/sbin/runscript
+# Copyright 1999-2004 Gentoo Foundation
+# Distributed under the terms of the GNU General Public License v2
+# $Header: /var/cvsroot/gentoo-x86/www-servers/tengine/files/tengine.init-r2,v 1.1 2010/01/03 19:51:41 djc Exp $
 
-. /etc/rc.conf
-. /etc/rc.d/functions
+extra_started_commands="upgrade reload"
+extra_commands="configtest"
 
-function check_config {
-  stat_busy "Checking tengine configuration"
-  /usr/sbin/tengine -t -q -c /etc/tengine/tengine.conf
-  if [ $? -ne 0 ]; then
-    stat_die
-  else
-    stat_done
-  fi
+depend() {
+	need net
+	use dns logger netmount
 }
 
-case "$1" in
-  start)
-    check_config
-    $0 careless_start
-    ;;
-  careless_start)
-    stat_busy "Starting tengine"
-    if [ -s /var/run/tengine.pid ]; then
-      stat_fail
-      # probably ;)
-      stat_busy "Tengine is already running"
-      stat_die
-     fi
-    /usr/sbin/tengine -c /etc/tengine/tengine.conf &>/dev/null
-    if [ $? -ne 0 ]; then
-      stat_fail
-    else
-      add_daemon tengine
-      stat_done
-    fi
-    ;;
-  stop)
-    stat_busy "Stopping tengine"
-    PID=$(cat /var/run/tengine.pid)
-    kill -QUIT $PID &>/dev/null
-    if [ $? -ne 0 ]; then
-      stat_fail
-    else
-      for i in {1..10}; do
-        [ -d /proc/$PID ] || { stat_done; rm_daemon tengine; exit 0; }
-        sleep 1
-      done
-      stat_fail
-    fi
-    ;;
-  restart)
-    check_config
-    $0 stop
-    sleep 1
-    $0 careless_start
-    ;;
-  reload)
-    check_config
-    if [ -s /var/run/tengine.pid ]; then
-      status "Reloading tengine configuration" kill -HUP $(cat /var/run/tengine.pid)
-    fi
-    ;;
-  check)
-    check_config
-    ;;
-  *)
-    echo "usage: $0 {start|stop|restart|reload|check|careless_start}"
-esac
+start() {
+	configtest || return 1
+	ebegin "Starting tengine"
+	start-stop-daemon --start --pidfile /var/run/tengine.pid \
+		--exec /usr/sbin/tengine -- -c /etc/tengine/tengine.conf
+	eend $? "Failed to start tengine"
+}
+
+stop() {
+	configtest || return 1
+	ebegin "Stopping tengine"
+	start-stop-daemon --stop --pidfile /var/run/tengine.pid
+	eend $? "Failed to stop tengine"
+	rm -f /var/run/tengine.pid
+}
+
+reload() {
+	configtest || return 1
+	ebegin "Refreshing tengine' configuration"
+	kill -HUP `cat /var/run/tengine.pid` &>/dev/null
+	eend $? "Failed to reload tengine"
+}
+
+upgrade() {
+	configtest || return 1
+	ebegin "Upgrading tengine"
+
+	einfo "Sending USR2 to old binary"
+	kill -USR2 `cat /var/run/tengine.pid` &>/dev/null
+
+	einfo "Sleeping 3 seconds before pid-files checking"
+	sleep 3
+
+	if [ ! -f /var/run/tengine.pid.oldbin ]; then
+		eerror "File with old pid not found"
+		return 1
+	fi
+
+	if [ ! -f /var/run/tengine.pid ]; then
+		eerror "New binary failed to start"
+		return 1
+	fi
+
+	einfo "Sleeping 3 seconds before WINCH"
+	sleep 3 ; kill -WINCH `cat /var/run/tengine.pid.oldbin`
+
+	einfo "Sending QUIT to old binary"
+	kill -QUIT `cat /var/run/tengine.pid.oldbin`
+
+	einfo "Upgrade completed"
+
+	eend $? "Upgrade failed"
+}
+
+configtest() {
+	ebegin "Checking tengine' configuration"
+	mkdir -p /tmp/tengine
+	/usr/sbin/tengine -c /etc/tengine/tengine.conf -tq
+	eend $? "failed, please correct errors above"
+}
